comment: false
github_checks:
  annotations: true

coverage:
  precision: 2
  range: '20...60'
  round: down
  status:
    changes: false
    patch:
      default:
        informational: true
    project:
      default:
        target: auto
        threshold: 5%

flags:
  cassiopeia:
    paths:
      - packages/cassiopeia/
  source-dom:
    paths:
      - packages/source-dom/
  vite:
    paths:
      - packages/vite/
  vue:
    paths:
      - packages/vue/
