name: release

on:
  push:
    tags:
      - 'v*'

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    uses: ./.github/workflows/workflow-call-context.yaml
    permissions:
      contents: read
  ci:
    if: needs.context.outputs.environment == 'production'
    uses: ./.github/workflows/workflow-call-ci.yaml
    needs:
      - context
    permissions:
      contents: read
    with:
      ref: ${{ needs.context.outputs.ref }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      upload: true
  release:
    if: needs.context.outputs.environment == 'production'
    runs-on: ubuntu-latest
    needs:
      - context
      - ci
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.context.outputs.ref }}
          fetch-depth: 0
      - name: restore lib cache
        uses: actions/download-artifact@v3
        with:
          name: lib
          path: packages
      - name: write .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: pnpm release
        run: |
          pnpm run release -- ${{ needs.context.outputs.version }}
      - name: github release
        run: |
          pnpm exec changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
